version: '3.7'

services:
  mysql.ecommerce.dev:
    build: ./docker/mysql
    container_name: mysql.ecommerce.dev
    restart: always
    tty: true
    command: --innodb-use-native-aio=0
    ports:
      - "3306:3306"
    volumes:
      - "db.ecommerce:/var/lib/mysql"
    environment:
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ecommerce

volumes:
  db.ecommerce: